### ISSUE TITLE
Wrong docker image in pipeline.py

### ISSUE THREAD

**Issue by MKCarter** [APAJanssen/KinaseDocker2#1]
I have noticed that the `pipeline.py` script actually points to the old KinaseDocker docker image:

```
self.docker_kwargs = dict(image='kinasedocker_v1_0',
                                  runtime='nvidia',
                                  device_requests=[dev_req(device_ids=['0'], capabilities=[['gpu']])])
```

I have modified this for the CLI version and it works:

```
self.docker_kwargs = dict(image='apajanssen/kinasedocker2',
                                  runtime='nvidia',
                                  device_requests=[dev_req(device_ids=['0'], capabilities=[['gpu']])])
```

For the pymol plugin, the `pipeline.py` script is locked.

Could you please update?

Many Thanks,
Mike

**Comment by APAJanssen** [comment]
Hi Mike,

Thank you for pointing this out and including the fix! This was indeed yet to be updated after pushing it onto Docker Hub as a public resource. It should now be fixed in the main branch.

Thanks for the input!

Anthe
